id: I2AADFD54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:49:05+00:00'
last_modified: '2022-06-08T08:23:08.392900+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22310
  title: སུམ་རྟགས་ཀྱི་ས་བཅད་དང་རྩ་བ་ཕྱོགས་གཅིག་ཏུ་སྤེལ་བ་འོད་དཀར་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC08:
      image_group_id: I1KG10543
      title: ''
      total_pages: 14
      order: 1
      base_file: CC08.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
