id: P008271
initial_creation_type: ocr
source_metadata:
  id: bdr:W22310
  title: སུམ་རྟགས་ཀྱི་ས་བཅད་དང་རྩ་བ་ཕྱོགས་གཅིག་ཏུ་སྤེལ་བ་འོད་དཀར་སྣང་བ།
  author: ''
  volumes:
    6b4d353a6dd8431c905d7ee23163f58f:
      image_group_id: I1KG10543
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
